### ISSUE TITLE
locutions

### ISSUE THREAD

**Issue by OdysseusPolymetis** [oeuvres/Alix#3]
Choisir entre <b>"Monsieur Proust"</b> et <b>"Monsieur | Proust"</b>
Risque de perte d'informations dans le cas du regroupement (valeur conceptuelle de certains éléments de locution, ex. "rue de la Justice") MAIS
Moins efficace pour détection d'entités nommées

**Comment by glorieux-f** [comment]
Semble OK, ne pas oublier pour ne pas refaire.
